Consume Secure Flag On New Address Reported
ONSdigital/census-rm-case-processor pull request #209
Opened 2020-09-24 09:02 UTC by LeoKHoward

# Motivation and Context
We want to record a property as secure so that future visits can be arranged if required

# What has changed
New boolean secureType in Address DTO...can only be true or false (not null)
Checks if case metadata exists and if so what the secureEstablishment flag is set to
Test

# How to test?
Build with other branches on card and run ATs

# Links
https://trello.com/c/4fnNI9lZ/1231-consume-secure-flag-on-newaddressreported-5
https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?pageId=40216113

2020-09-24 09:26 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [Consume secure flag on newAddressReported (5)](https://trello.com/c/4fnNI9lZ/1231-consume-secure-flag-on-newaddressreported-5)

2020-09-24 12:36 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/casesvc/model/dto/Address.java
> +  private boolean secureType;
I've been testing... it seems like this is fatal if there's no `secureType` supplied in the JSON, or a null is supplied.

In other words, what value is it supposed to use if it's not `true` or `false`? Like `null` or no value present at all? What then? So far as I can see... it blows up pretty badly.

2020-09-24 12:36 UTC, NickGrantONS submitted a review, later dismissed
Can't use a Java primitive when value might be null or not present at all in the JSON: guaranteed to cause problems

2020-09-24 13:01 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/casesvc/model/dto/Address.java
> +  private boolean secureType;
actually it might be ok...

2020-09-24 13:12 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/casesvc/model/dto/Address.java
> +  private boolean secureType;
okay, so the primitive thing does default to `false` but in that sense, we have no idea whether a value was supplied or not. This doesn't meet the requirements.

2020-09-24 13:16 UTC, NickGrantONS requested changes
The requirement says, basically, "if the secure marker is supplied on the event, use it, otherwise copy the value from the source case".

That's not what's been implemented.

In order to know whether or not a value was supplied on the event, we'll have to use the `Optional` class. A dodgy hack we've used elsewhere is to use `Boolean` instead of `boolean` and assume that null means that no value was supplied, which is not strictly correct, but I'd accept that if you do it that way.

Then, once you know whether a value was supplier or **not** you can implement the business logic to use the value (true or false) if and when it was supplied, else take the value from the source case.

You can't use defaults for this feature, because it makes "false was supplied" and "we defaulted to false" indistinguishable, which doesn't allow for the value to be _not_ supplied, so the source case value is used.

Hope that's as clear as it can be.

2020-09-29 11:04 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/casesvc/service/NewAddressReportedService.java
> -    newCase.setMetadata(metadataFromSourceCase(sourceCase.getMetadata()));
by removing this and using the `getMetadataFromEventOrSourceCase` we are potentially going to lose the `channel` metadata which would have been copied over - I see that as a bug

2020-09-29 11:06 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/casesvc/service/NewAddressReportedService.java
> -    newCase.setMetadata(metadataFromSourceCase(sourceCase.getMetadata()));
actually, I checked the original code, and it had the 'bug' too

2020-09-29 15:46 UTC, NickGrantONS approved these changes

2020-09-30 08:15 UTC, ryangrundy7 approved these changes
LGTM 👍

2020-09-30 10:10 UTC, merged