AddressTypeChange for CE Case ceActualResponses Defaulted to Zero
ONSdigital/census-rm-case-processor pull request #213
Opened 2020-10-06 08:26 UTC by LeoKHoward

# Motivation and Context
When an AddressTypeChange event occurs where the new address is a CE Case, the ceActualResponses is null rather than 0 

# What has changed
Default set to 0 rather than null
Test

# How to test?
Maven clean install on branch and check image builds and tests pass

# Links
https://trello.com/c/DUgevj8y

2020-10-06 08:27 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [CE case missing ceActualResponses](https://trello.com/c/DUgevj8y/1494-ce-case-missing-ceactualresponses)

2020-10-08 11:50 UTC, NickGrantONS requested changes
I think there's a better approach. See comments.

2020-10-08 11:50 UTC, NickGrantONS commented on src/main/java/uk/gov/ons/census/casesvc/service/AddressTypeChangeService.java
> +    if (newCase.getCaseType().equals("CE")) {
Why only do this for CE cases? Are we taking the wrong approach completely. We could change `ceActualResponses` from an `Integer` to an `int` and save ourselves headache.

Could do the same with `ceExpectedCapacity` - make it an `int` and save ourselves a bunch of weird null pointer exceptions.

2020-10-19 17:14 UTC, NickGrantONS approved these changes
Looks good. I wonder if we're going to get null pointer exceptions when people start sending us new cases with null `ceActualResponses` but that's their problem, not ours

2020-10-21 13:16 UTC, ryangrundy7 approved these changes

2020-10-22 07:35 UTC, merged