Receipting Bug Fix When AR > ER
ONSdigital/census-rm-case-processor pull request #226
Opened 2021-01-06 12:57 UTC by LeoKHoward

# Motivation and Context
UPDATE message being sent to Field when AR > ER which shouldn't happen

# What has changed
Now follows these rules:

- AR < ER (Send UPDATE)
- AR = ER (Send CANCEL)
- AR > ER (Send nothing)
- ER = null (Send nothing)

# How to test?
Build image and run ATs
Load a sample and set the actualResponses/expected and check the variations send (or don't send) the correct output

# Links
https://trello.com/c/OEL6bfx5

2021-01-06 12:57 UTC, LeoKHoward commented
![](https://github.trello.services/images/mini-trello-icon.png) [Sending updates to field when the AR>ER](https://trello.com/c/OEL6bfx5/1779-sending-updates-to-field-when-the-arer)

2021-01-07 09:36 UTC, ryangrundy7 approved these changes
LGTM 👍

2021-01-07 09:36 UTC, ryangrundy7 commented on src/main/java/uk/gov/ons/census/casesvc/service/CaseReceiptService.java
> +    // If case is already receipted we dont ned to tell Field about any more responses
Spelling mistake

2021-01-07 09:46 UTC, LeoKHoward commented on src/main/java/uk/gov/ons/census/casesvc/service/CaseReceiptService.java
> +    // If case is already receipted we dont ned to tell Field about any more responses
Damn

2021-01-07 10:06 UTC, LukeLoze1 requested changes

2021-01-07 10:11 UTC, LukeLoze1 reviewed
It works fine btw, but if you're leaving in the newer function can you rename it to note it can also receipt the case.

2021-01-07 11:54 UTC, LukeLoze1 approved these changes

2021-01-07 12:34 UTC, merged